### ISSUE TITLE
control_point shouldn't loop endlessly

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#122]
Currently `control_point` is a `loop` which is effectively a spinlock on atomics. If, for example, thread `T1` starts tracing `Location` `L` and thread `T2` also wanted to start tracing `L1` at example the same time, then one of the threads will spin until the other has finished tracing. Fixing this "just" involves thinking about which conditions don't need to loop (probably most of them) and which do.

**Comment by vext01** [comment]
In my branch, the thread late to the party would hit a break.

But while we are here, having re-read the spinlock blog post, I'm still not sold on the idea of rolling our own spinlock. It looks to me like modern Mutex implementations are good and the code would be vastly simplified (and obviously correct) by using a Mutex instead of a spinlock. Thoughts?

**Comment by ltratt** [comment]
Those two issues are connected. When https://github.com/softdevteam/yk/pull/121 is finished, I'll have a look at this stuff.

**Comment by vext01** [comment]
OK. But to be clear the merge point doesn't loop endlessly.

If a thread fails to update the pack from `COUNTING` to `TRACING`, then the next time around the loop it will load a `TRACING` (as set by the other thread) and exit the loop.

**Comment by ltratt** [comment]
This issue isn't really relevant given the change in code since it was raised.
