### ISSUE TITLE
Abort or unwind?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#225]
We currently only support `abort` as a panic strategy but is this viable in the long term? I suspect that a small, but gradually growing, amount of Rust code will start to make use of `unwind` as a panic strategy. Is shifting difficult? Should we do it? Or ...?

**Comment by bjorn3** [comment]
cg_clif doesn't support it either. In most cases this is fine. The only exception I had was an older version of proc_macro2 that checks if it is running inside a proc macro by calling a proc macro only function and catching the panic if it isn't running inside a proc macro. Newer versions use a function of proc_macro that returns a bool.

Adding unwind support requires .eh_frame writing in combination with a eh_personality function that diverts to a landing pad. (for yorick running the black hole interpreter and pretending that no cleanup was necessary would also work I think.)

**Comment by ltratt** [comment]
That's interesting: my impression was that a small amount of code might come to rely on `catch_unwind` but it sounds like you're not seeing much of that in practise?

**Comment by bjorn3** [comment]
Yeah, proc_macro2 was the only one for which it is important. It is also used in hyper and servo for fault-tollerance to prevent a panic from bringing down the process. In addition wasmtime uses unwinding to handle traps inside the jitted wasm module. Proc_macro2 is the only case I have seen where `catch_unwind` would actually catch something in the "happy" case. This is probably due to the fact that panicking is relatively costly compared to `Result` and that unless you use `resume_unwind` (which most people don't know about I think) it results in a panic message on stderr.

**Comment by bjorn3** [comment]
Oh and I forget the countless tests in the rustc test suite that use panics to test the drop order.

**Comment by ltratt** [comment]
Thanks @bjorn3! I'm going to close this, because you've convinced me it's not something that we need to worry about yet.
